### ISSUE TITLE
[Feature Request] Dark Theme

### ISSUE THREAD

**Issue by ArthurPatriot** [creativetimofficial/ct-soft-ui-dashboard-pro#19]
### What is your enhancement?
Are you planning to add dark theme for this product?

**Comment by ghwebdesign** [comment]
I see that a dark mode has been implemented in a recent release and I love it. Thank you!!! 

Is there any documentation on how to set up the dark mode toggle to maintain the dark setting across all pages in a session until the user manually toggles it back? 

Thanks!

**Comment by rarestoma** [comment]
Hi @ghwebdesign,

Thank you for working with our products, we are happy to hear that you like our dark theme.

To add the dark mode, you have to add `dark-version` class to the body tag.

Please let me know if it works.

Best regards,
Rares

**Comment by jaymegordo** [comment]
@rarestoma I see the dark mode toggle switch calls the js function `darkMode` which seems add the `dark-version` tags. How do we keep dark mode enabled for the entire session until the user toggles it back? I could easily store a `current_theme` setting in the db, but how do we make the pages always respect that on load instead of defaulting to the light mode.

Eg I want a website that works exactly how you think it should, either light or dark mode that the user can toggle at will. Thanks!
