### ISSUE TITLE
Logo icon gets collapsed

### ISSUE THREAD

**Issue by sagarsoni7** [creativetimofficial/ct-soft-ui-dashboard-pro#4]
Logo width gets affected when sidebar is collapsed

- When uncollapsed
<img width="722" alt="Screenshot 2021-06-20 at 10 55 59 PM" src="https://user-images.githubusercontent.com/29792913/122683114-e2252580-d21a-11eb-82e7-533ea0c61059.png">

- When collapsed
<img width="722" alt="Screenshot 2021-06-20 at 10 55 52 PM" src="https://user-images.githubusercontent.com/29792913/122683117-e4877f80-d21a-11eb-8a66-63ad1b23389a.png">

**Comment by sagarsoni7** [comment]
Also, this just looks weird. Better render some icon instead of first letter
<br/>
<img width="128" alt="Screenshot 2021-06-20 at 11 00 20 PM" src="https://user-images.githubusercontent.com/29792913/122683194-4e078e00-d21b-11eb-8fda-7a62cd6a61aa.png">

**Comment by rarestoma** [comment]
Hi @sagarsoni7,

Thank you for working with our products.

I tried to replicate it in Chrome on macOS but I didn't succeed. Can you please tell me what device and browser did you use so I can test it and see how can we fix this?

Thank you,
Rares

**Comment by groovemen** [comment]
Hello @sagarsoni7,

Thank you for using our products and for letting us know about this issue. We are now working on the product update and we will integrate the fix for the affected icon. I will also talk with my colleagues related to your suggestion about rendering icons instead of the first letter. 
Please let us know if we can help with any other details.
All the best, 
Stefan

**Comment by sagarsoni7** [comment]
@rarestoma @groovemen - Now even I am unable replicate it. Earlier it was on Chrome on macOS. 

Something must have been wrong at my side. Sorry
